env:
  scenario: "cim"
  topology: "toy.4p_ssdd_l0.0"
  durations: 1120
  state_shaping:
    look_back: 7
    max_ports_downstream: 2
  experience_shaping:
    time_window: 100
    fulfillment_factor: 1.0
    shortage_factor: 1.0
    time_decay_factor: 0.97
training:
  max_episode: 200
  exploration:
    parameter_names:
      - "epsilon"
    split_ep: 100
    start_values: 0.4
    mid_values: 0.32
    end_values: 0.0
agent:
  model:
    hidden_dims:
      - 256
      - 128
      - 64
    output_dim: 21   # number of possible actions
    softmax: false
    batch_norm: true
    skip_connection: false
    dropout_p: 0.0
  optimizer:
    lr: 0.05
  scheduler:
    step_size: 10
    gamma: 0.1
  hyper_params:
    reward_discount: .0
    min_exp_to_train: 1024
    num_batches: 10
    batch_size: 128
    target_update_freq: 5
    tau: 0.1
    is_double: true
    per_sample_td_error: true
  seed: 16  # for reproducibility
multi_process:
  enable: true
  redis:
    hostname: "localhost"
    port: 6379
  group: "test"
  num_actors: 2 
  inference_mode: "local"  # supported: "local", "remote"
  receive_action_timeout: 100  # milliseconds
  max_receive_action_attempts: 1
  allowed_null_responses: 15
  update_trigger: 2
  inference_trigger: 2
