redis:
  hostname: "localhost"
  port: 6379
group: 2vbbhf
peers:
  learner: 
    actor: 2
  actor:
    learner: 1 
inference_mode: "remote"  # supported: "local", "remote"
receive_action_timeout: 100  # milliseconds
max_receive_action_attempts: 1
update_trigger: 1
inference_trigger: 1
