redis:
  hostname: "localhost"
  port: 6379
group: test_group
num_actors: 1
inference_mode: "local"  # supported: "local", "remote"
receive_action_timeout: 100  # milliseconds
max_receive_action_attempts: 1
update_trigger: 2
inference_trigger: 2
