experiment_name: "lp_verification"
seed: 1024
env:
  scenario: "ecr"
  topology: "5p_ssddd_l0.7"
  max_tick: 224
lp:
  plan_window_size: 224
  time_decay:
    enable: true
    time_decay_factor: 0.99999999
  dump_file_prefix: 'lp_solution'