mode: process
name: test # str: name of the training job

components: # component config
  actor:
    num: 5 # int: number of this component
    command: "python /home/yaqiu/maro/examples/cim/dqn/distributed/actor_launcher.py" # str: command to be executed 
  learner:
    num: 1
    command: "python /home/yaqiu/maro/examples/cim/dqn/distributed/learner_launcher.py"