env:
  scenario: "cim"
  topology: "toy.4p_ssdd_l0.0"
  durations: 1120
  state_shaping:
    look_back: 7
    max_ports_downstream: 2
  experience_shaping:
    time_window: 100
    fulfillment_factor: 1.0
    shortage_factor: 1.0
    time_decay_factor: 0.97
training:
  max_episode: 100
  warmup_ep: 20
  k: 5
  perf_thresh: 0.95   # minimum performance (fulfillment ratio) required to trigger early stopping
agent:
  seed: 1024   # for reproducibility
  type: "actor_critic"  # "actor_critic" or "policy_gradient"
  actor_model:
    output_dim: 21
    hidden_dims:
      - 256
      - 128
      - 64
    softmax: true
    batch_norm: false
  actor_optimizer:
    lr: 0.001
  critic_model:
    output_dim: 1
    hidden_dims:
      - 256
      - 128
      - 64
    softmax: false
    batch_norm: true
  critic_optimizer:
    lr: 0.001
  reward_discount: .0
  actor_critic_hyper_parameters:
    train_iters: 10
    actor_loss_coefficient: 0.1
    k: 1
    lam: 0.0
    # clip_ratio: 0.8
