experiment_name: "randday_sumr"
env:
  scenario: "citi_bike"
  topology: "c1"
  start_tick: 0
  durations: 14400 # stop until the data steam end
  snapshot_resolution: 20
  transfer_cost: 0.1
train:
  enable: true
  rollout_cnt: 3000
  batch_size: 1024
  gamma: 0.99
  freq: 1
  exp_replay:
      flush: 8
model:
  device: "cuda:1"
  emb_dim: 16
save_code_after: 3 # -1 is not save, any positive number is after which episode the code is saved.

