env:
  seed: 10
  scenario: "cim"
  topology: "global_trade.22p_l0.8"
  # topology: "toy.4p_ssdd_l0.0"
  durations: 200
agent:
  hyper_params:
    reward_discount: 0.99
    num_batches: 1
    batch_size: 16
    td_steps: 100
    actor_loss_coefficient: 0.1
    entropy_factor: 0.1
  model:
    device: "cpu"
    path: "./" 
    scale: 4
    sequence_buffer_size: 20
    hidden_size: 32
    port_edge_feature_dim: 1 
    vessel_edge_feature_dim: 2
    port_pre_dim: 16
    vessel_pre_dim: 8
    policy_hidden_dims: 
      - 16
    value_hidden_dims:
      - 16
    graph_output_dim: 32
    action_dim: 21
    learning_rate: 0.00005
    feature:
      # temporal or random, if temporal, the edges in the graph are listed in the order of event time, else in a
      # random order.
      attention_order: temporal
      onehot_identity: False
training:
  enable: true
  max_episode: 500
  train_freq: 1
  model_save_freq: 1
log:
  path: "./"
  exp:
    enable: false
    freq: 10
multi_process:
  enable: true
  group: "dfwtehf"
  num_actors: 2
  inference_mode: "remote"  # supported: "local", "remote"
  receive_action_timeout: 100  # milliseconds
  max_receive_action_attempts: 1
  allowed_null_responses: 15
  update_trigger: 2
  inference_trigger: 2