
name: coverage

on: [ push, pull_request, workflow_dispatch ]

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel twine
    - name: Install build dependencies
      run: | 
        pip install -r maro/requirements.build.txt
    - name: Compile cython files
      run: |
        cython ./maro/backends/backend.pyx ./maro/backends/np_backend.pyx ./maro/backends/raw_backend.pyx ./maro/backends/frame.pyx -3 -E FRAME_BACKEND=NUMPY,NODES_MEMORY_LAYOUT=ONE_BLOCK -X embedsignature=True
    - name: Build wheel on Windows and macOS
      if: runner.os == 'Windows' || runner.os == 'macOS'
      run: |
        python setup.py bdist_wheel
    - name: Build manylinux wheel
      if: runner.os == 'Linux' && matrix.python-version == '3.6'
      uses: RalfG/python-wheels-manylinux-build@v0.3.1-manylinux2010_x86_64
      with:
        python-versions: 'cp36-cp36m cp37-cp37m'
        build-requirements: 'numpy'
        pip-wheel-args: '-w ./wheelhouse' # save wheel packages to wheelhouse folder
    - name: Move valid packages to dist folder for manylinux
      if: runner.os == 'Linux' && matrix.python-version == '3.6'
      run: |
        mkdir -p dist
        cp wheelhouse/pymaro-*-manylinux*.whl dist
    - name: Build source package on linux
      if: runner.os == 'Linux' && matrix.python-version == '3.6'
      run: |
        python setup.py sdist 
    - name: Generate coverage report
      run: |
        pip install pytest
        pip install pytest-cov
        pytest --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        files: ./coverage1.xml,./coverage2.xml
        directory: ./coverage/reports/
        flags: unittests
        env_vars: OS,PYTHON
        name: maro-code-coverage
        fail_ci_if_error: true
        path_to_write_report: ./coverage/codecov_report.gz
